version: '3.7'

services:
  db:
    networks:
      - devops
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
   
    environment:
      MYSQL_DATABASE: formation3
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: 
      MYSQL_INITDB_SCRIPT: /docker-entrypoint-initdb.d/formation3.sql
      
    
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    volumes:
      - ./my-datavolume:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    restart: on-failure
  backenddevops:
    networks:
      - devops
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/formation3?createDatabaseIfNotExist=true&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    container_name: backenddevops
    build: 
      dockerfile: DockerFileBack
      context: "./"
    ports:
       - "5000:8081"
    links:
       - "db"
    depends_on:
      db:
        condition : service_healthy
    restart: on-failure
  
volumes:
   my-datavolume:
networks:
  devops: 
